# mongodb configuration
spring.application.name=ResQNet
spring.mongodb.uri=mongodb://localhost:27017/ResQNetdb
spring.data.mongodb.auto-index-creation=true

# spring ai configuration
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.response-mime-type=application/json
spring.ai.google.genai.chat.temperature=0.2
spring.ai.google.genai.chat.max-output-tokens=200